language: node_js
node_js: 
  - node
script: 
  - "npm run build:yuque"
cache: 
  directories: 
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: MarvinXu/marvinxu.github.io
  target_branch: master
  local_dir: public
  on:
    branch: main